### ISSUE TITLE
Bug: Panic when fetching timestamp in registry for not existing manifest

### ISSUE THREAD

**Issue by nikolai-fra** [nniikkoollaaii/k8s-find-outdated-images#6]
Following Panic:
```
panic: GET https://xxx.azurecr.io/v2/xxxxx/manifests/xxx: MANIFEST_UNKNOWN: manifest tagged by "xxx" is not found; map[Tag:xxx]

goroutine 1 [running]:
main.getImageCreatedTimestampForImage({0xc000410c40, 0x3c})
	/home/runner/work/k8s-find-outdated-images/k8s-find-outdated-images/query_container_registry.go:31 +0x1c6
main.queryTimestamps(...)
	/home/runner/work/k8s-find-outdated-images/k8s-find-outdated-images/query_container_registry.go:15
main.findOutdatedImages(0xc000420380?)
	/home/runner/work/k8s-find-outdated-images/k8s-find-outdated-images/main.go:217 +0x2d8
main.main.func2(0xc0003d3d40?)
	/home/runner/work/k8s-find-outdated-images/k8s-find-outdated-images/main.go:182 +0x19
github.com/urfave/cli/v2.(*Command).Run(0xc0003d3d40, 0xc000335d40)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunContext(0xc0002a31e0, {0x16d7830?, 0xc000048088}, {0xc00003a180, 0x17, 0x18})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
main.main()
	/home/runner/work/k8s-find-outdated-images/k8s-find-outdated-images/main.go:188 +0x34d
```

The Manifest does not exist in the Registry
(The corresponding pod is in a Pending-State because of a ImagePullBackOff)

The app should not crash in this case!

**Comment by nniikkoollaaii** [comment]
Fixed with v1.2.2
